from flask import Flask, render_template, session, request, redirect, send_file
import google.generativeai as genai
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import os, io
import json

app = Flask(__name__)
app.secret_key = "travelbot"

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
model = genai.GenerativeModel("models/gemini-flash-latest")

PERSIST_DIRECTORY = "db/chroma_db"

if not os.path.exists(PERSIST_DIRECTORY):
    raise ValueError("Vector database not found. Run ingestion.py first.")

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

db = Chroma(
    persist_directory=PERSIST_DIRECTORY,
    embedding_function=embeddings
)


def retrieve_context(query: str, city: str):
    retriever = db.as_retriever(
        search_kwargs={
            "k": 5,
            "filter": {"city": city.lower()}
        }
    )

    docs = retriever.invoke(query)

    if not docs:
        return "No verified tourism data found."

    context = "\n".join([doc.page_content for doc in docs])
    return context


def generate_itinerary(data):

    query = f"""
    Travel information about {data['city']}
    Budget: {data['budget']}
    Travel Type: {data['travel_type']}
    Food Preference: {data['food']}
    """

    retrieved_context = retrieve_context(query, data["city"])

    prompt = f"""
You are a professional travel planner.

Use ONLY the following verified tourism information:

{retrieved_context}

STRICT RULES:
- DO NOT use markdown
- DO NOT add extra text
- OUTPUT VALID JSON ONLY

Create a {data['days']}-day travel plan for {data['city']}.

JSON FORMAT (strictly follow):

{{
  "itinerary": [
    {{
      "day": "Day 1",
      "location": "Location name",
      "morning": "Morning activity",
      "afternoon": "Afternoon activity",
      "evening": "Evening activity",
      "stay": "Hotel name",
      "expense": "Estimated daily expense"
    }}
  ],
  "hotels": [
    {{
      "name": "Hotel name",
      "description": "Short description"
    }}
  ],
  "food": [
    {{
      "place": "Restaurant name",
      "specialty": "Famous dish"
    }}
  ]
}}
"""

    response = model.generate_content(prompt)
    text = response.text.strip()

    try:
        result = json.loads(text)
    except json.JSONDecodeError:
        raise ValueError("Invalid JSON generated by model.")

    return result["itinerary"], result["hotels"], result["food"]

@app.route("/")
def home():
    return render_template("index.html")


@app.route("/bot", methods=["GET", "POST"])
def bot():

    QUESTIONS = [
        ("name", "Hi 👋 Before we begin, may I know your name?"),
        ("city", "Which city are you planning to visit?"),
        ("days", "How many days will you be staying?"),
        ("budget", "What’s your budget range?"),
        ("travel_type", "What kind of travel do you prefer?"),
        ("food", "Food preference?"),
        ("spare_time", "Any spare time available? (If none, type No)"),
    ]

    if request.method == "GET":
        session.clear()
        session["step"] = 0
        session["data"] = {}
        session["chat"] = [{"sender": "bot", "text": QUESTIONS[0][1]}]

        return render_template("bot.html", chat=session["chat"], show_input=True)

    answer = request.form.get("answer", "").strip()

    session["chat"].append({"sender": "user", "text": answer})

    step = session["step"]
    key = QUESTIONS[step][0]
    session["data"][key] = answer

    session["step"] += 1
    step = session["step"]

    if step >= len(QUESTIONS):
        itinerary, hotels, food_places = generate_itinerary(session["data"])

        session["result"] = {
            "itinerary": itinerary,
            "hotels": hotels,
            "food_places": food_places,
        }

        return redirect("/result")

    session["chat"].append({"sender": "bot", "text": QUESTIONS[step][1]})

    return render_template("bot.html", chat=session["chat"], show_input=True)


@app.route("/result")
def result():
    result = session.get("result")

    if not result:
        return redirect("/bot")

    return render_template(
        "result.html",
        itinerary=result["itinerary"],
        hotels=result["hotels"],
        food_places=result["food_places"],
    )

@app.route("/download-pdf")
def download_pdf():
    result = session.get("result")
    data = session.get("data")

    if not result or not data:
        return redirect("/bot")

    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    y = height - 50

    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(50, y, "Travel Itinerary")
    y -= 30

    pdf.setFont("Helvetica", 11)
    pdf.drawString(50, y, f"Traveler: {data.get('name')}")
    y -= 18
    pdf.drawString(50, y, f"City: {data.get('city')}")
    y -= 18
    pdf.drawString(50, y, f"Days: {data.get('days')}")
    y -= 25

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Day-wise Itinerary")
    y -= 20

    pdf.setFont("Helvetica", 11)

    for day in result["itinerary"]:
        if y < 100:
            pdf.showPage()
            y = height - 50

        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(50, y, day["day"])
        y -= 15

        pdf.setFont("Helvetica", 11)
        pdf.drawString(70, y, f"Location: {day['location']}")
        y -= 15
        pdf.drawString(70, y, f"Morning: {day['morning']}")
        y -= 15
        pdf.drawString(70, y, f"Afternoon: {day['afternoon']}")
        y -= 15
        pdf.drawString(70, y, f"Evening: {day['evening']}")
        y -= 15
        pdf.drawString(70, y, f"Stay: {day['stay']}")
        y -= 20

    if y < 150:
        pdf.showPage()
        y = height - 50

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Hotel Recommendations")
    y -= 20

    pdf.setFont("Helvetica", 11)
    for hotel in result["hotels"]:
        pdf.drawString(70, y, f"- {hotel['name']}: {hotel['description']}")
        y -= 15

    if y < 150:
        pdf.showPage()
        y = height - 50

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Food Recommendations")
    y -= 20

    pdf.setFont("Helvetica", 11)
    for food in result["food_places"]:
        pdf.drawString(70, y, f"- {food['place']}: {food['specialty']}")
        y -= 15

    pdf.save()
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="travel_itinerary.pdf",
        mimetype="application/pdf"
    )


if __name__ == "__main__":
    app.run(debug=True)